from enum import StrEnum


class FailureCode(StrEnum):
    NONE = "NONE"
    RUN_FAILED = "RUN_FAILED"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    REPEATED_FAILURE = "REPEATED_FAILURE"
    REGRESSION_DETECTED = "REGRESSION_DETECTED"
    DEPLOY_FATAL = "DEPLOY_FATAL"
    SESSION_STATE_ERROR = "SESSION_STATE_ERROR"
    COMPILE_FAILED = "COMPILE_FAILED"
    PATCH_REJECTED = "PATCH_REJECTED"
    BOOT_TIMEOUT_ROLLBACK = "BOOT_TIMEOUT_ROLLBACK"
