from enum import StrEnum


class FailureCode(StrEnum):
    NONE = "NONE"
    RUN_FAILED = "RUN_FAILED"
    EVIDENCE_FAIL = "EVIDENCE_FAIL"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    REPEATED_FAILURE = "REPEATED_FAILURE"
    REGRESSION_DETECTED = "REGRESSION_DETECTED"
    DEPLOY_FATAL = "DEPLOY_FATAL"
    SESSION_STATE_ERROR = "SESSION_STATE_ERROR"
    COMPILE_FAILED = "COMPILE_FAILED"
    PATCH_REJECTED = "PATCH_REJECTED"
    BOOT_TIMEOUT_ROLLBACK = "BOOT_TIMEOUT_ROLLBACK"
    DUPLICATE_PATCH = "DUPLICATE_PATCH"
    KERNEL_DEAD_NO_SHELL = "KERNEL_DEAD_NO_SHELL"
    TRANSPORT_UNRECOVERABLE = "TRANSPORT_UNRECOVERABLE"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    VERIFICATION_REGRESSION = "VERIFICATION_REGRESSION"
    VERIFICATION_STUCK = "VERIFICATION_STUCK"
