#!/usr/bin/env python3
"""gen_manifest.py — 重生成 code/rpi5/manifest.yaml（cross-device 共享机械护栏）。

apply 编辑 code/rpi5 后运行本脚本重生成 manifest.yaml（patch↔workspace 结构映射），
供 sync-code-to-doc 读取为文档源、供 AI 维护 code/rpi5/README.md 文件映射表。
原 sync-workspace-to-code 的 --gen-manifest-only 入口迁移至此（该 skill 已删除，
workspace→code 归档方向消亡，本脚本仅保留 manifest 重生成能力）。
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[5]))
from harness.lib.harness_lib import (
    log_info, log_error,
    harness_init, harness_exit,
)
from harness.lib.paths import path as profile_path


def _unregistered_patch_paths(patch_root: Path, manifest_path: Path) -> list[str]:
    """检测 code/rpi5 存在但 manifest.yaml 未登记的 patch 文件（方向 5）。

    门禁语义：manifest 是 patch↔workspace 映射的单一事实源，源码/构建文件
    （如 LcIod/Makefile 引用的 lciod_read_logic.c）漏登记即该文件不随批次
    同步到 workspace，Makefile 已引用而 manifest 漏登的静默断链此前无感。
    本函数以现有 manifest 登记集合为基准，扫描 kernel/aosp/others 实际文件
    求差集，返回未登记相对路径列表（空 = 已全覆盖）。
    """
    if not manifest_path.is_file():
        return []
    registered = set()
    for m in re.finditer(r"^\s*-\s+patch:\s+(\S+)",
                         manifest_path.read_text(encoding="utf-8"), re.M):
        registered.add(m.group(1))
    actual = set()
    for section in ("kernel", "aosp", "others"):
        base = patch_root / section
        if not base.is_dir():
            continue
        for f in base.rglob("*"):
            if f.is_file():
                actual.add(str(f.relative_to(patch_root).as_posix()))
    return sorted(actual - registered)


def generate_manifest(patch_root: Path, check_only: bool,
                      kernel_deletions: list[str],
                      aosp_deletions: list[str]) -> bool:
    """从 patch_root（code/rpi5）现状扫描，重生成 manifest.yaml。

    - kernel/aosp 的 modified/new 段：patch 相对路径 + source workspace 路径映射
    - deletions 段：旧归档流程产物，新流程无删除对齐来源（CLI 固定传空）
    - others 段：source 恒为 null
    - check_only 时不写盘（manifest 缺失/有变化仅报告）
    - 返回 ok：False = 内容为空/异常（P2-8：此前静默 exit 0，apply 收尾
      误判成功——PATCHS_DIR 配错正是现实场景，须如实失败）
    """
    manifest_path = patch_root / "manifest.yaml"

    # 未登记判红门禁（方向 5）：code/rpi5 存在但 manifest 未登记的 patch
    # 文件。check_only（校验）模式下判红返回 False；正常重生成模式下列出
    # 并提示将登记（重生成天然全覆盖，不阻断写盘）。
    unregistered = _unregistered_patch_paths(patch_root, manifest_path)
    if unregistered:
        log_error(f"manifest 未登记 {len(unregistered)} 个 code/rpi5 文件"
                  f"（未登记即判红门禁）：")
        for rel in unregistered:
            log_error(f"  {rel}")
        if check_only:
            return False
        log_info(f"重生成将登记 {len(unregistered)} 个新文件")

    lines: list[str] = []
    lines.append("# Auto-generated by gen_manifest.py — patch↔workspace 结构映射。")
    lines.append("# 禁止手动编辑。README.md（人类可读）由 AI 基于此文件维护。")
    lines.append("")

    for section, ws_root in [("kernel", "rpi5-kernel-build/common"),
                             ("aosp", "aosp")]:
        section_emitted = False
        for sub in ("modified", "new"):
            dir_path = patch_root / section / sub
            if not dir_path.is_dir():
                continue
            files: list[str] = []
            for f in sorted(dir_path.rglob("*")):
                if not f.is_file():
                    continue
                rel = str(f.relative_to(dir_path).as_posix())
                files.append(rel)
            if not files:
                continue
            if not section_emitted:
                lines.append(f"{section}:")
                section_emitted = True
            lines.append(f"  {sub}:")
            for rel in files:
                src = rel[:-5] if sub == "modified" and rel.endswith(".diff") else rel
                lines.append(f"    - patch: {section}/{sub}/{rel}")
                lines.append(f"      source: {ws_root}/{src}")

    # deletions 段
    if kernel_deletions or aosp_deletions:
        lines.append("deletions:")
        if kernel_deletions:
            lines.append("  kernel:")
            for f in kernel_deletions:
                lines.append(f"    - source: rpi5-kernel-build/common/{f}")
        if aosp_deletions:
            lines.append("  aosp:")
            for f in aosp_deletions:
                lines.append(f"    - source: aosp/{f}")

    # others 段
    others_dir = patch_root / "others"
    if others_dir.is_dir():
        others_files = sorted(
            str(f.relative_to(others_dir).as_posix())
            for f in others_dir.rglob("*")
            if f.is_file()
        )
        if others_files:
            lines.append("others:")
            for rel in others_files:
                lines.append(f"  - patch: others/{rel}")
                lines.append("    source: null")

    content = "\n".join(lines) + "\n"

    if not content.strip():
        log_error("manifest 内容为空（PATCHS_DIR 下无 kernel/aosp/others 内容？"
                  "核对 harness/config/paths.conf），中止更新")
        return False

    if manifest_path.is_file() and manifest_path.read_text(encoding="utf-8") == content:
        log_info("manifest.yaml 无变化")
        return True

    if check_only:
        # 方向 2：有变化判红（此前仅 log_info 返 True，selfcheck 接入后
        # manifest_rc 依据此返回值——有变化/未登记均须非零透出拒收据）
        log_error("manifest.yaml 有变化（仅检查模式，未写入；有变化即判红，"
                  "须运行重生成后再提交）")
        return False

    from cdp_paths import atomic_write_text
    atomic_write_text(manifest_path, content)  # 原子写（P1-2 口径统一）
    log_info("manifest.yaml 已更新")
    return True


def _mark_gen_manifest():
    """自发 gen_manifest 打点：清单重生成完成即 mark，供收据 edit 段细分。

    进程内直调 emit_mark（B8/C-1 打点胶水收敛，与 selfcheck 同款；batch
    识别走 CDP_BATCH_ID/current-batch.json 回落）；发点失败仅 stderr 提示，
    不改返回码（打点诊断数据，非清单生成结果本身）。
    """
    timing_dir = Path(__file__).resolve().parent
    if str(timing_dir) not in sys.path:
        sys.path.insert(0, str(timing_dir))
    try:
        import cdp_timing
        if not cdp_timing.emit_mark("gen_manifest"):
            print("warn: gen_manifest 打点失败（不阻断）", file=sys.stderr)
    except Exception as e:
        print(f"warn: gen_manifest 打点失败（不阻断）: {e}", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="重生成 code/rpi5/manifest.yaml（cross-device 编辑后护栏）"
    )
    parser.add_argument("--check-only", action="store_true",
                        help="仅检查，不写盘（有变化时报告）")
    args = parser.parse_args()

    harness_init("gen_manifest")

    patch_root = profile_path("PATCHS_DIR")
    ok = generate_manifest(patch_root, check_only=args.check_only,
                           kernel_deletions=[], aosp_deletions=[])
    if not args.check_only:
        # 方向 4：check_only 不发点——selfcheck 内调 gen_manifest --check-only
        # 做 manifest_rc 门禁时，若发 gen_manifest mark 会与 apply_selfcheck
        # mark 交错劫持（致三段 0.0）；check-only 非真实重生成，无 edit 段
        # 归因意义。仅实际重生成（写盘）才打点。
        _mark_gen_manifest()
    harness_exit(0 if ok else 1)


if __name__ == "__main__":
    main()
