#!/usr/bin/env python3
"""gen_manifest.py — 重生成 code/rpi5/manifest.yaml（cross-device 共享机械护栏）。

apply 编辑 code/rpi5 后运行本脚本重生成 manifest.yaml（patch↔workspace 结构映射），
供 sync-code-to-doc 读取为文档源、供 AI 维护 code/rpi5/README.md 文件映射表。
原 sync-workspace-to-code 的 --gen-manifest-only 入口迁移至此（该 skill 已删除，
workspace→code 归档方向消亡，本脚本仅保留 manifest 重生成能力）。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[5]))
from harness.lib.harness_lib import (
    log_info, log_error,
    harness_init, harness_exit,
)
from harness.lib.paths import path as profile_path


def generate_manifest(patch_root: Path, check_only: bool,
                      kernel_deletions: list[str],
                      aosp_deletions: list[str]) -> None:
    """从 patch_root（code/rpi5）现状扫描，重生成 manifest.yaml。

    - kernel/aosp 的 modified/new 段：patch 相对路径 + source workspace 路径映射
    - deletions 段：旧归档流程产物，新流程无删除对齐来源（CLI 固定传空）
    - others 段：source 恒为 null
    - check_only 时不写盘（manifest 缺失/有变化仅报告）
    """
    manifest_path = patch_root / "manifest.yaml"

    lines: list[str] = []
    lines.append("# Auto-generated by gen_manifest.py — patch↔workspace 结构映射。")
    lines.append("# 禁止手动编辑。README.md（人类可读）由 AI 基于此文件维护。")
    lines.append("")

    for section, ws_root in [("kernel", "rpi5-kernel-build/common"),
                             ("aosp", "aosp")]:
        section_emitted = False
        for sub in ("modified", "new"):
            dir_path = patch_root / section / sub
            if not dir_path.is_dir():
                continue
            files: list[str] = []
            for f in sorted(dir_path.rglob("*")):
                if not f.is_file():
                    continue
                rel = str(f.relative_to(dir_path).as_posix())
                files.append(rel)
            if not files:
                continue
            if not section_emitted:
                lines.append(f"{section}:")
                section_emitted = True
            lines.append(f"  {sub}:")
            for rel in files:
                src = rel[:-5] if sub == "modified" and rel.endswith(".diff") else rel
                lines.append(f"    - patch: {section}/{sub}/{rel}")
                lines.append(f"      source: {ws_root}/{src}")

    # deletions 段
    if kernel_deletions or aosp_deletions:
        lines.append("deletions:")
        if kernel_deletions:
            lines.append("  kernel:")
            for f in kernel_deletions:
                lines.append(f"    - source: rpi5-kernel-build/common/{f}")
        if aosp_deletions:
            lines.append("  aosp:")
            for f in aosp_deletions:
                lines.append(f"    - source: aosp/{f}")

    # others 段
    others_dir = patch_root / "others"
    if others_dir.is_dir():
        others_files = sorted(
            str(f.relative_to(others_dir).as_posix())
            for f in others_dir.rglob("*")
            if f.is_file()
        )
        if others_files:
            lines.append("others:")
            for rel in others_files:
                lines.append(f"  - patch: others/{rel}")
                lines.append("    source: null")

    content = "\n".join(lines) + "\n"

    if not content.strip():
        log_error("manifest 内容为空，中止更新")
        return

    if manifest_path.is_file() and manifest_path.read_text(encoding="utf-8") == content:
        log_info("manifest.yaml 无变化")
        return

    if check_only:
        log_info("manifest.yaml 有变化（仅检查模式，未写入）")
        return

    manifest_path.write_text(content, encoding="utf-8")
    log_info("manifest.yaml 已更新")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="重生成 code/rpi5/manifest.yaml（cross-device 编辑后护栏）"
    )
    parser.add_argument("--check-only", action="store_true",
                        help="仅检查，不写盘（有变化时报告）")
    args = parser.parse_args()

    harness_init("gen_manifest")

    patch_root = profile_path("PATCHS_DIR")
    generate_manifest(patch_root, check_only=args.check_only,
                      kernel_deletions=[], aosp_deletions=[])
    harness_exit(0)


if __name__ == "__main__":
    main()
